name: Lint, Build & Check Style on Commit and PRs
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build check
